### ISSUE TITLE
toc dropdown does not scroll on overflow

### ISSUE THREAD

**Issue by jdeisenberg** [ryan-roemer/sphinx-bootstrap-theme#153]
I have a very long toc at http://langintro.com/cljsbook ; if you view it in a small browser window (or on a small monitor), the entire "Chapters" TOC does not display; it is cut off at the bottom of the browser window. It would be good if it would scroll on overflow.

**Comment by ryan-roemer** [comment]
Talked with a CSS-savvy colleague of mine and here's what she came up with:

### Option One -- Modern Browsers

If you're using modern browsers that support `vh` and `calc()` (aka http://caniuse.com/#feat=viewport-units) then you can add in a custom CSS extension with:

```css
.dropdown-menu.globaltoc {
  max-height: calc(100vh - 50px); /* 50px is "whatever $("#navbar") height is" */
  overflow: scroll;
}
```
### Option One -- Ye Olde Browsers Too

If you're supporting old browsers then you can do a CSS addition of one part:

```css
.dropdown-menu.globaltoc {
  overflow: scroll;
}
```

and then complement that with added JS:

```js
$(".dropdown-menu.globaltoc").height(
  $(window).height() - $("#navbar").height()
);
```

Let me know how it goes! If you're finding it works well, I'd accept a PR for the more-backwards-compatible-even-if-kludgy option two.
